### ISSUE TITLE
Build packages for OSX on release

### ISSUE THREAD

**Issue by josegonzalez** [miku/zek#15]
It would be awesome if you could cross-compile zek for use on OSX :)

**Comment by miku** [comment]
Thanks for the suggestion! I added a cross-compiled binary to the [latest release](https://github.com/miku/zek/releases/tag/v0.1.9).

```
$ curl -sLO zek https://git.io/JvbaX && chmod +x zek
```

Or do you mean something like a new  [formula](https://github.com/Homebrew/homebrew-core/tree/master/Formula) in [brew](https://brew.sh/)?


----

Note-to-self:
```
$ GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -v -o zek cmd/zek/main.go
```

**Comment by josegonzalez** [comment]
Great, that works just fine :)
