### ISSUE TITLE
Issue with the debian package

### ISSUE THREAD

**Issue by suntong** [miku/zek#17]
Having installed the `zek_0.1.10_amd64.deb` file:

```sh
$ zek
bash: zek: command not found

$ /usr/sbin/zek
bash: /usr/sbin/zek: Permission denied
```

The reason:

```sh
$ ls -l /usr/sbin/zek
-rw-r--r-- 1 root root 6377472 2020-11-04 06:07 /usr/sbin/zek
```

**Comment by miku** [comment]
Thanks for reporting, this should be fixed now. I replaced the current 0.1.10 version debian package with the fixed one:

> https://github.com/miku/zek/releases/download/v0.1.10/zek_0.1.10_amd64.deb

**Comment by suntong** [comment]
Yes!
Thanks!
