### ISSUE TITLE
xml attribute with underscore and number breaks zek

### ISSUE THREAD

**Issue by scrivy** [miku/zek#18]
```
$ echo '<Yo _30day="aoeu" />' | zek
2021/08/16 19:36:06 5:1: expected '}', found 30
```
The resulting struct is something like
```
type Yo struct {
  30day string
}
```
which causes go fmt to throw the `expected '}'` error since struct field names cannot start with a number.

**Comment by miku** [comment]
Thanks for the bug report, it should be fixed in [0.1.11](https://github.com/miku/zek/releases/tag/v0.1.11).
