### ISSUE TITLE
Feature request: provide a flag to specify the output file (make it usable with go:generate)

### ISSUE THREAD

**Issue by breml** [miku/zek#19]
We would like to use `zek` with `go generate`. For this to work, we need a possibility to specify the target file (instead of printing the result to stdout). An additional flag, which allows to specify the target file for the output would be very helpful.

**Comment by breml** [comment]
Additionally, the generated code should contain something like this (accept the package name as argument/flag):

```
// Generated by zek; DO NOT EDIT.

package {{ .PackageName }}

import (
	"encoding/xml"
)

```

**Comment by miku** [comment]
I understand the use case, but (ensouled by papers like [cat -v](http://harmful.cat-v.org/cat-v/unix_prog_design.pdf)) I'm asking myself, if we need another flag (there are lots already).

At least for the moment, you can work around the issue by invoking the shell directly, e.g. like this:

* [Is it possible to redirect stdin/stdout with go:generate](https://stackoverflow.com/a/32144586/89391)
* [minimal example in a gist](https://gist.github.com/miku/2bbdd40a3668140fad86b260896d4888#file-main-go)

Would that work for you?

**Comment by miku** [comment]
@breml Yes, your second comment was my thought exactly - you might need a valid package with a given name. I think that would be useful.

**Comment by breml** [comment]
The two examples you are providing assume, that everyone has `sh` or `bash` available, which is not necessarily the case (e.g. Windows).

**Comment by miku** [comment]
I hope 0.1.12 improves usability in the context of go generate.

* https://github.com/miku/zek/releases/tag/v0.1.12
* https://github.com/miku/zek#generate-a-package

**Comment by breml** [comment]
@miku Thank you very much for your fast response and the updated version.

In regards to the "autogenerated comment", there is an official recommendation for this sort of comments in the Go ecosystem, which is documented in [Generate Go files by processing source](https://pkg.go.dev/cmd/go#hdr-Generate_Go_files_by_processing_source) (History: https://github.com/golang/go/issues/13560).

The regex pattern is defined as:

```none
^// Code generated .* DO NOT EDIT\.$
```

So for zek this would be: `// Code generated zek DO NOT EDIT.`

Comments following this recommendation are also recognizes by all sorts of tools in the Go ecosystem (e.g. linters) so I strongly recommend to follow this guide line.

**Comment by breml** [comment]
One additional thing: from the diff in https://github.com/miku/zek/commit/3121649b5e1ec8715bf182ed1d20edb193c5da99#diff-1f7a66282d4e5972df450ba732e9ac27f815ff032972f1a19871cb9365d06973R117-R123 it looks to me, that

* between the package comment  and `package ...` there is no empty line, so the package comment in fact becomes the documentation of the package. I assue, this is not inteded.
* If the package comment is not provided (that is, if it is `""`), there will be an empty line before `package ...`, which is not how `gofmt` would format it.

(I did not yet run the new version, but only had a quick glance at the commits.)

**Comment by miku** [comment]
Thanks for noticing, I fixed this detail. Also, I removed the flag to change the comment.

```go
$ zek -P somepkg < testdata/w.14.xml 
// Code generated by zek; DO NOT EDIT.

package somepkg

import "encoding/xml"

// List was generated 2021-09-16 20:08:33 by tir on trieste.
type List struct {
        XMLName xml.Name `xml:"list"`
        Text    string   `xml:",chardata"`
        Value   []string `xml:"value"`
}

```

Released with [0.1.14](https://github.com/miku/zek/releases/tag/v0.1.14)

**Comment by breml** [comment]
@miku Thanks again for the new functionality, as well as the pre built releases (#20). This works great.

I just found two minor issues you might want to fix:

1. If I generate a file using the `-o` and `-P` flags, the resulting file has an unnecessary additional newline at the end of the file. I assume the reason is the usage of `fmt.Println` on line https://github.com/miku/zek/blob/master/cmd/zek/main.go#L175 instead of just `fmt.Print`. On line https://github.com/miku/zek/blob/master/cmd/zek/main.go#L171 the code gets formatted according to the Go standards, so there is no need for an additional newline at the end of the file.
2. I downloaded the binary release 0.1.14. If I run `zek -version` it still prints `0.1.13`.

And sorry for the delay with my response.

**Comment by miku** [comment]
Thanks for the details, these reports are very helpful - I hope the two remaining issues are resolved with [0.1.15](https://github.com/miku/zek/releases/tag/v0.1.15).

**Comment by breml** [comment]
@miku Thanks again for the latest version v0.1.15. I can confirm, that the two issues are resolved.

While running the our CI pipelines with the last version of zek, I discovered an other issue:

In order to make sure that the respective commit contains up to date versions of the automatically generated source files we run `go generate` in our CI pipeline and we expect, that after `go generate` is executed, the git repository is not "dirty" (this is, there are no altered or additional files in comparison to the respective commit). This currently causes an issue with `zek`, because the banner comment in front of the generated struct changes everytime zek is executed (time, user, host). (see: https://github.com/miku/zek/blob/ac31c01b3e185eb93cd44fc818196fe8322d6964/structwriter.go#L120)

To prevent our pipeline from failing, I would need an option to suppress the generation of this banner (or replace it with a static text like `%s was generated automatically.`

**Comment by miku** [comment]
I added a boolean `-B` flag that when set will use a static text for reproducible builds (and the comment would conform to conventions). 

```go
$ zek -B -P mypkg < fixtures/c.xml 
// Code generated by zek; DO NOT EDIT.

package mypkg

import "encoding/xml"

// A was generated automatically.
type A struct {
        XMLName xml.Name `xml:"a"`
        Text    string   `xml:",chardata"`
        B       []string `xml:"b"`
}
```

Please find the this feature in [0.1.16](https://github.com/miku/zek/releases/tag/v0.1.16) and onward.

Thank for your help to make zek more usable.

**Comment by breml** [comment]
@miku Fantastic job, thank you very much.
