### ISSUE TITLE
Consider pre built releases for the major platforms

### ISSUE THREAD

**Issue by breml** [miku/zek#20]
It would be very convenient if this project could provide pre built releases for the major platforms (in particular, I am interested in linux amd64 releases for simple integration in Docker containers) e.g. via [GoReleaser](https://goreleaser.com/).

GoReleaser does support packaging `rpm` and `deb` as well. So the whole release process can be simplified and streamlined.

**Comment by miku** [comment]
Yes, I saw GoReleaser and it may help.

**Comment by miku** [comment]
Starting to test GoRelease with [0.1.13](https://github.com/miku/zek/releases/tag/v0.1.13) - hope this helps.

**Comment by breml** [comment]
Thanks for the additional binary releases.
