### ISSUE TITLE
Increase perf by removing reflection

### ISSUE THREAD

**Issue by gedw99** [miku/zek#24]
There is a way to parse xml and bind to a strict without using any reflection.

It can also be extended to generate the golang structs from the xml.

If you’re interested let me know. The lib is used by many golang xml projects . Battle proven

**Comment by miku** [comment]
Thanks for the idea, while faster is surely always better, it has not been such a bottleneck so far (even with GBs of XML).

**Comment by miku** [comment]
If there's an open source library for faster xml handling in Go I'm gladly take a look.
