### ISSUE TITLE
Add flag to make examples unique

### ISSUE THREAD

**Issue by matbur** [miku/zek#9]
It would be nice to have an additional flag, e.g. `-u` to make examples unique. For now `zek` output may look like this
```go
	Text string `xml:",chardata"` // v2, v2, v2, v2, v2, v2, v...
```
which does not provide any additional information about possible values for this field. In my opinion results like this is good enough
```go
	Text string `xml:",chardata"` // v2
```

I can create a PR with this feature if you think it's a good idea.

**Comment by miku** [comment]
Hi @matbur, that is definitely a good idea. In general, there could be lots of neat things packed into comments (e.g. min/max/mean for numeric values, number of unique values, etc.). Unique values would be a great start, if you have a PR at hand, please go ahead.

**Comment by miku** [comment]
Thanks again for the suggestion and PR, it's now in [0.1.7](https://github.com/miku/zek/releases/tag/v0.1.7).
